import { SupportedLanguage } from "../types";

// Extract dominant colors synchronously or fallback
export function extractPaletteFromDataUrl(dataUrl: string): string[] {
  return ["#0F172A", "#1E293B", "#3B82F6", "#8B5CF6", "#F8FAFC"];
}

// Detect visual elements from design context
export function detectElementsFromContext(context: string): string[] {
  return [
    "Navigation Header",
    "Hero Banner",
    "Call to Action Button",
    "Analytics KPI Card",
    "Interactive Search Input",
    "Responsive Grid Container",
    "Footer Links"
  ];
}

// Extract dominant colors from an image base64 using an offscreen canvas
export async function extractPaletteFromImage(imageBase64: string): Promise<string[]> {
  return new Promise((resolve) => {
    try {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          resolve(["#0F172A", "#1E293B", "#3B82F6", "#8B5CF6", "#F8FAFC"]);
          return;
        }

        canvas.width = 100;
        canvas.height = 100;
        ctx.drawImage(img, 0, 0, 100, 100);

        const imgData = ctx.getImageData(0, 0, 100, 100).data;
        const colorCounts: Record<string, number> = {};

        for (let i = 0; i < imgData.length; i += 16) {
          const r = Math.round(imgData[i] / 32) * 32;
          const g = Math.round(imgData[i + 1] / 32) * 32;
          const b = Math.round(imgData[i + 2] / 32) * 32;
          const hex = `#${((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1).toUpperCase()}`;
          colorCounts[hex] = (colorCounts[hex] || 0) + 1;
        }

        const sorted = Object.entries(colorCounts)
          .sort((a, b) => b[1] - a[1])
          .map((entry) => entry[0])
          .slice(0, 5);

        if (sorted.length < 3) {
          resolve(["#0F172A", "#1E293B", "#3B82F6", "#8B5CF6", "#FFFFFF"]);
        } else {
          resolve(sorted);
        }
      };
      img.onerror = () => {
        resolve(["#0F172A", "#1E293B", "#3B82F6", "#8B5CF6", "#F8FAFC"]);
      };
      img.src = imageBase64;
    } catch {
      resolve(["#0F172A", "#1E293B", "#3B82F6", "#8B5CF6", "#F8FAFC"]);
    }
  });
}

// Simple code beautifier/formatter
export function formatCode(code: string, language: string): string {
  try {
    if (language.toLowerCase() === "json") {
      return JSON.stringify(JSON.parse(code), null, 2);
    }
    // General indentation cleaner
    const lines = code.split("\n");
    let indentLevel = 0;
    const formatted = lines.map((rawLine) => {
      const line = rawLine.trim();
      if (!line) return "";
      if (line.match(/^[}\])]/) || line.startsWith("</")) {
        indentLevel = Math.max(0, indentLevel - 1);
      }
      const indented = "  ".repeat(indentLevel) + line;
      if (
        (line.endsWith("{") || line.endsWith("(") || line.endsWith("[") || (line.startsWith("<") && !line.startsWith("</") && !line.endsWith("/>") && !line.includes("</"))) &&
        !line.startsWith("<!--")
      ) {
        indentLevel++;
      }
      return indented;
    });
    return formatted.join("\n");
  } catch {
    return code;
  }
}

// Intelligent heuristic code generation for fallback or instant offline preview
export function generateHeuristicCode(
  language: SupportedLanguage,
  framework: string,
  detectedElements: string[],
  colors: string[],
  customPrompt?: string
): string {
  const primaryColor = colors[2] || "#3B82F6";
  const darkBg = colors[0] || "#0F172A";
  const surfaceBg = colors[1] || "#1E293B";

  switch (language.id) {
    case "react-jsx":
      return `import React, { useState } from 'react';

/**
 * Generated by CodeVision AI
 * Framework: ${framework}
 * Detected: ${detectedElements.join(', ')}
 */
export default function GeneratedView() {
  const [activeItem, setActiveItem] = useState(0);

  return (
    <div className="min-h-screen bg-[${darkBg}] text-slate-100 p-6 flex flex-col items-center justify-center font-sans antialiased">
      <div className="w-full max-w-4xl bg-[${surfaceBg}] border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-6">
        {/* Navigation Bar */}
        <header className="flex items-center justify-between border-b border-slate-800/80 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-[${primaryColor}] flex items-center justify-center font-bold text-white shadow-lg">
              CV
            </div>
            <div>
              <h2 className="text-base font-semibold text-white">App Navigation</h2>
              <p className="text-xs text-slate-400">Semantic React Component</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="px-3 py-1.5 text-xs rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 transition">
              Action
            </button>
            <button className="px-3 py-1.5 text-xs rounded-lg bg-[${primaryColor}] hover:opacity-90 text-white font-medium transition">
              Get Started
            </button>
          </div>
        </header>

        {/* Dynamic Grid / Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { title: 'Feature Alpha', subtitle: 'Automated layout detection', badge: 'Active' },
            { title: 'Feature Beta', subtitle: 'Responsive CSS Grid & Flexbox', badge: 'New' },
            { title: 'Feature Gamma', subtitle: 'Modern semantic tokens', badge: 'Ready' }
          ].map((item, index) => (
            <div 
              key={index}
              onClick={() => setActiveItem(index)}
              className={\`p-4 rounded-xl border transition cursor-pointer \${
                activeItem === index 
                  ? 'border-[${primaryColor}] bg-slate-800/50 ring-1 ring-[${primaryColor}]' 
                  : 'border-slate-800 bg-slate-900/40 hover:border-slate-700'
              }\`}
            >
              <div className="flex justify-between items-start">
                <span className="text-xs font-mono text-[${primaryColor}] font-semibold">0{index + 1}</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-800 text-slate-300 font-medium">
                  {item.badge}
                </span>
              </div>
              <h3 className="mt-3 text-sm font-semibold text-white">{item.title}</h3>
              <p className="mt-1 text-xs text-slate-400">{item.subtitle}</p>
            </div>
          ))}
        </div>

        {/* Interactive Form Controls */}
        <div className="border-t border-slate-800 pt-4 flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <input 
              type="text" 
              placeholder="Search or enter query..." 
              className="px-3.5 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-[${primaryColor}]"
            />
            <button className="px-3 py-1.5 text-xs rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200">
              Filter
            </button>
          </div>
          <p className="text-xs text-slate-500">
            Rendered with dynamic state hooks
          </p>
        </div>
      </div>
    </div>
  );
}`;

    case "vue":
      return `<template>
  <div class="view-wrapper">
    <div class="card-container">
      <header class="header">
        <div class="brand">
          <div class="logo">CV</div>
          <div>
            <h3>Vue 3 Component</h3>
            <p>Single File Component with Composition API</p>
          </div>
        </div>
        <button class="cta-button" @click="handleAction">Action</button>
      </header>

      <section class="grid">
        <div 
          v-for="(card, i) in items" 
          :key="i" 
          class="item-card"
          :class="{ active: selectedIndex === i }"
          @click="selectedIndex = i"
        >
          <h4>{{ card.title }}</h4>
          <p>{{ card.desc }}</p>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const selectedIndex = ref(0);
const items = ref([
  { title: 'Reactive State', desc: 'Managed via ref() hooks' },
  { title: 'Scoped Styling', desc: 'Modern CSS custom properties' },
  { title: 'Component Tree', desc: 'Clean template hierarchy' }
]);

function handleAction() {
  alert('Vue interaction triggered');
}
</script>

<style scoped>
.view-wrapper {
  min-height: 100vh;
  background-color: ${darkBg};
  color: #f8fafc;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1.5rem;
  font-family: sans-serif;
}
.card-container {
  width: 100%;
  max-width: 48rem;
  background: ${surfaceBg};
  border: 1px solid #334155;
  border-radius: 1rem;
  padding: 1.5rem;
}
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #334155;
  padding-bottom: 1rem;
}
.brand {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}
.logo {
  width: 2.25rem;
  height: 2.25rem;
  background: ${primaryColor};
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
}
.cta-button {
  background: ${primaryColor};
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  cursor: pointer;
}
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  margin-top: 1.5rem;
}
.item-card {
  background: #0f172a;
  border: 1px solid #1e293b;
  border-radius: 0.75rem;
  padding: 1rem;
  cursor: pointer;
  transition: all 0.2s;
}
.item-card.active {
  border-color: ${primaryColor};
  box-shadow: 0 0 0 1px ${primaryColor};
}
</style>`;

    case "flutter":
      return `import 'package:flutter/material.dart';

void main() {
  runApp(const CodeVisionApp());
}

class CodeVisionApp extends StatelessWidget {
  const CodeVisionApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF0F172A),
        primaryColor: const Color(0xFF3B82F6),
      ),
      home: const GeneratedScreen(),
    );
  }
}

class GeneratedScreen extends StatefulWidget {
  const GeneratedScreen({super.key});

  @override
  State<GeneratedScreen> createState() => _GeneratedScreenState();
}

class _GeneratedScreenState extends State<GeneratedScreen> {
  int _selectedCardIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('CodeVision UI Screen'),
        backgroundColor: const Color(0xFF1E293B),
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {},
          )
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header Card
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(20.0),
              decoration: BoxDecoration(
                color: const Color(0xFF1E293B),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: const Color(0xFF334155)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Converted Visual Wireframe',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Elements: ${detectedElements.slice(0, 3).join(", ")}',
                    style: const TextStyle(fontSize: 13, color: Colors.grey),
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF3B82F6),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    child: const Text('Primary Action'),
                  )
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}`;

    case "python":
      return `"""
CodeVision AI - Generated Python GUI Interface
Target: Streamlit Interactive Application
Detected Elements: ${detectedElements.join(", ")}
"""

import streamlit as st

st.set_page_config(page_title="Converted Interface", layout="wide")

# Custom CSS matching detected color palette
st.markdown("""
<style>
    .stApp {
        background-color: ${darkBg};
        color: #F8FAFC;
    }
    .metric-card {
        background-color: ${surfaceBg};
        padding: 1.5rem;
        border-radius: 0.75rem;
        border: 1px solid #334155;
    }
</style>
""", unsafe_allow_html=True)

st.title("Converted UI Application")
st.caption("Generated with CodeVision AI Image to Code Engine")

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Total Conversions", "1,248", "+14%")
with col2:
    st.metric("Active Sessions", "420", "+5%")
with col3:
    st.metric("API Health", "99.9%", "Optimal")

st.divider()

user_query = st.text_input("Enter Search or Prompt:", placeholder="Filter records...")
if st.button("Submit Query", type="primary"):
    st.success(f"Processing query: {user_query}")
`;

    case "json":
      return JSON.stringify(
        {
          schemaVersion: "1.0.0",
          component: "ScreenView",
          layout: "FlexColumn",
          theme: {
            palette: {
              background: darkBg,
              surface: surfaceBg,
              primary: primaryColor,
              text: "#F8FAFC",
              muted: "#94A3B8",
            },
            borderRadius: "12px",
            spacingBase: 8,
          },
          detectedElements: detectedElements,
          children: [
            {
              type: "HeaderBar",
              title: "CodeVision Converted UI",
              hasAction: true,
            },
            {
              type: "CardGrid",
              columns: 3,
              items: [
                { title: "Metric Card", value: "$48,290" },
                { title: "Active Users", value: "1,420" },
                { title: "Uptime", value: "99.9%" },
              ],
            },
            {
              type: "Button",
              variant: "primary",
              label: "Get Started",
            },
          ],
        },
        null,
        2
      );

    case "sql":
      return `-- CodeVision AI - Relational Database Schema derived from UI
-- Generated entities based on visual layout

CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    language VARCHAR(50) NOT NULL,
    framework VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ui_components (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    component_type VARCHAR(100) NOT NULL,
    label VARCHAR(255),
    display_order INT DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Seed mock data based on detected elements
INSERT INTO projects (name, description, language, framework) 
VALUES ('Dashboard Project', 'UI Layout generated from wireframe', '${language.name}', '${framework}');

${detectedElements.map((el, i) => `INSERT INTO ui_components (project_id, component_type, label, display_order) VALUES ((SELECT id FROM projects LIMIT 1), '${el}', '${el} Component', ${i + 1});`).join("\n")}
`;

    default:
      // Standard HTML5 + Tailwind CSS
      return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Converted UI - CodeVision AI</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Plus Jakarta Sans', sans-serif; }
  </style>
</head>
<body class="bg-[${darkBg}] text-slate-100 min-h-screen p-4 sm:p-6 lg:p-8 flex items-center justify-center">
  <main class="w-full max-w-4xl bg-[${surfaceBg}] border border-slate-800 rounded-2xl p-6 sm:p-8 shadow-2xl space-y-6">
    <!-- Header Section -->
    <header class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-5">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-[${primaryColor}] flex items-center justify-center text-white font-bold shadow-lg">
          ⚡
        </div>
        <div>
          <h1 class="text-lg font-bold text-white tracking-tight">CodeVision AI Converted View</h1>
          <p class="text-xs text-slate-400">Target: ${language.name} • ${framework}</p>
        </div>
      </div>
      <div class="flex items-center gap-2">
        <span class="px-2.5 py-1 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
          Semantic Code
        </span>
      </div>
    </header>

    <!-- Detected UI Elements Grid -->
    <section class="space-y-3">
      <h2 class="text-xs font-semibold uppercase tracking-wider text-slate-400">Recognized Components</h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        ${detectedElements
          .map(
            (element, idx) => `
        <div class="p-4 rounded-xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition">
          <div class="flex items-center justify-between">
            <span class="text-xs font-mono text-[${primaryColor}] font-semibold">#0${idx + 1}</span>
            <span class="w-2 h-2 rounded-full bg-emerald-400"></span>
          </div>
          <h3 class="mt-2 text-sm font-semibold text-white">${element}</h3>
          <p class="text-xs text-slate-400 mt-1">Responsive container with standard padding</p>
        </div>`
          )
          .join("")}
      </div>
    </section>

    <!-- Interactive Form Element -->
    <section class="bg-slate-900/40 border border-slate-800 rounded-xl p-5 space-y-4">
      <h3 class="text-sm font-semibold text-white">Input & Interactive Controls</h3>
      <div class="flex flex-wrap items-center gap-3">
        <input 
          type="text" 
          placeholder="Interactive test input..." 
          class="flex-1 min-w-[200px] px-3.5 py-2 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-[${primaryColor}]"
        >
        <button class="px-4 py-2 rounded-lg bg-[${primaryColor}] hover:opacity-90 text-white text-xs font-semibold shadow-md transition cursor-pointer">
          Primary Action
        </button>
        <button class="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium transition cursor-pointer">
          Secondary
        </button>
      </div>
    </section>

    <!-- Footer -->
    <footer class="pt-4 border-t border-slate-800 flex items-center justify-between text-xs text-slate-500">
      <span>Auto-generated by CodeVision AI</span>
      <span>Mobile & Desktop Ready</span>
    </footer>
  </main>
</body>
</html>`;
  }
}
