import JSZip from "jszip";
import { CodeFile } from "../types";

export async function exportProjectToZip(
  projectName: string,
  language: string,
  framework: string,
  primaryCode: string,
  files: CodeFile[],
  explanation?: string
): Promise<void> {
  const zip = new JSZip();

  // Root folder
  const folder = zip.folder(projectName.toLowerCase().replace(/[^a-z0-9]/g, "-") || "codevision-project");

  if (!folder) return;

  // Add primary file if files array is empty
  const fileExt = getFileExtension(language);
  const primaryFileName = getPrimaryFileName(language, fileExt);

  if (!files || files.length === 0) {
    folder.file(primaryFileName, primaryCode);
  } else {
    files.forEach((file) => {
      folder.file(file.name, file.content);
    });
    // Ensure primary file is present
    if (!files.some((f) => f.name === primaryFileName)) {
      folder.file(primaryFileName, primaryCode);
    }
  }

  // Create README.md
  const readmeContent = `# ${projectName}
Generated by **CodeVision AI – Image to Code Converter**

## Project Overview
- **Language**: ${language}
- **Framework / Styling**: ${framework}
- **Date**: ${new Date().toLocaleDateString()}

## Description
${explanation || "Production-ready UI code generated from image analysis with responsive layouts and semantic tags."}

## Getting Started
1. Review the generated source code in \`${primaryFileName}\`.
2. Install any required dependencies or open directly in your browser / IDE.
3. For HTML/Tailwind projects, open \`index.html\` directly in any modern browser.

---
Crafted with CodeVision AI.
`;

  folder.file("README.md", readmeContent);

  // Generate blob and trigger download
  const content = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(content);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${projectName.toLowerCase().replace(/\s+/g, "_") || "codevision_export"}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadSingleFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function getFileExtension(lang: string): string {
  switch (lang.toLowerCase()) {
    case "react jsx":
    case "react":
      return "jsx";
    case "vue.js":
    case "vue":
      return "vue";
    case "python":
      return "py";
    case "java":
      return "java";
    case "c#":
      return "cs";
    case "flutter / dart":
    case "flutter":
    case "dart":
      return "dart";
    case "javascript":
      return "js";
    case "css":
      return "css";
    case "sql":
      return "sql";
    case "json":
      return "json";
    case "php":
      return "php";
    default:
      return "html";
  }
}

function getPrimaryFileName(lang: string, ext: string): string {
  if (lang.toLowerCase().includes("react")) return `App.${ext}`;
  if (lang.toLowerCase().includes("vue")) return `Component.${ext}`;
  if (lang.toLowerCase().includes("flutter")) return `main.${ext}`;
  if (lang.toLowerCase().includes("python")) return `app.${ext}`;
  return `index.${ext}`;
}
